### ISSUE TITLE
Security Alert : Database

### ISSUE THREAD

**Issue by SidnaZayn** [Khadik86/dev_invofest23#79]
Permisi, sepertinya configurasi Firebase nya ([ini]( https://github.com/INVOFEST-PHB/dev_invofest23/blob/main/src/config/firebase/firebase.js )) masih terbuka di public (API Key, AuthDomain, dll). memungkinkan database disalah gunakan oleh orang lain.

saran saya, ada baiknya configurasi diletakan dalam .env lalu env dideklarasikan  di .gitignore atau repository lebih baik di private.

semoga sukses acaranya. good luck ~🍻

**Comment by Khadik86** [comment]
makasih bang telah mengoreksi kode kami 

iya bang itu niat nya sih cuman itu firebase masih tahap uji coba belm tahap production setelah nanti tahap production api nya yang production bukan api uji joba

**Comment by 0neSec** [comment]
@SidnaZayn
makasih bang telah mengoreksi kode kami

iya bang itu niat nya sih cuman itu firebase masih tahap uji coba belm tahap production setelah nanti tahap production api nya yang production bukan api uji joba

**Comment by SidnaZayn** [comment]
nice🤟. semoga sukses acaranya, semangat🔥
